### ISSUE TITLE
nickel-lang: failure with multiline string + variable interpolation

### ISSUE THREAD

**Issue by Jasha10** [tweag/topiary#501] opened 2023-06-07 23:26 UTC
**Describe the bug**
Formatting nickel-lang fails when variable interpolation is used with quotes in a multi-line string.

**To Reproduce**
Save the following nickel-lang file:
```nickel
# example.ncl
{
  name = "0.1.1",
  description = m%"
    The name is "%{name}"
  "%
}
```
Run topiary on the file:
```nickel
$ topiary --input-file example.ncl
# example.ncl
{
  name = "0.1.1",
  description = m%"
    The name is "%
      { name }
      "
  "
    %
  }
```
The output of topiary is not a valid nickel-lang file.

**Expected behavior**
Topiary should produce valid nickel-lang as output

**Environment**
 - OS name + version: Ubuntu 20.04 LTS
 - Version of the code:
```bash
$ topiary --version
topiary-cli 0.2.1
```

**Comment by Xophmeister** [comment] 2023-06-08 09:23
I cannot reproduce this in 61d076c216422 (which is post-0.2.1). I suspect it was fixed by the Nickel grammar update made in 0b43ffc539c06a, but I'll double-check...

**Comment by Xophmeister** [comment] 2023-06-08 09:29
...Confirmed.

@Jasha10 An immediate fix for this problem would be for you to checkout the latest `main` and rebuild. The Topiary Team will discuss whether to make a patch release.

**Comment by Jasha10** [comment] 2023-06-09 03:15
Thanks @Xophmeister.

**Closed** 2023-06-12 13:38 UTC
